### ISSUE TITLE
Ignore venv files in git

### ISSUE THREAD

**Issue by felix-hilden** [jengroff/projects#1]
Hello mate, I like to have a look at projects that are built with Tekore just to see what people are up to. I noticed that you just added the repo. It contains virtual environments with full versions of all packages that you use.

I get if you want to gather all your projects in one place, though I would advise you to still make separate repositories for them (and maybe use git subprojects if you must have them in one place), but more importantly, you can use a gitignore file to ignore all irrelevant files that are not specific to your projects, like `venv` folders. You can have a look at [our file](https://github.com/felix-hilden/tekore/blob/master/.gitignore) in Tekore, if you'd like a simple template.

If you are aware already, nevermind, but I thought I'd give a hint anyway :D Carry on!

**Comment by jengroff** [comment]
Thank you! I added the gitignore as you suggested.
